name: 🐛 Bug Report
description: For reporting code or design bugs with the software. DO NOT REPORT APACHE/NGINX/PHP CONFIGURATION ISSUES.
body:
- type: markdown
  attributes:
    value: |
        DO NOT REPORT ISSUES CONFIGURING: SSL, PHP, APACHE, NGINX, YOUR MACHINE, SSH, SFTP, ETC. ON THIS GITHUB TRACKER. 
        For assistance installing this software, as well as debugging issues with dependencies, please use our [Discord server](https://discord.gg/pterodactyl)
        You MUST complete all of the below information when reporting a bug, failure to do so will result in the closure of your issue. PLEASE stop spamming our tracker with "bugs" that are not related to this project.
        *To obtain logs for the panel and wings the below commands should help with the retrieval of them.*
        * **Panel:** `tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`
        * **Wings:** `sudo wings diagnostics`

- type: markdown
  attributes:
    value: |
        **Background**"

- type: dropdown
  id: panel-or-wings
  attributes:
    label: Panel or Wings
    options:
      - "Panel"
      - "Wings"
  validations:
    required: true

- type: input
  id: panel-version
  attributes:
    label: Panel Version
    description: Version number of your Panel (latest is not a version)
    placeholder: 1.x.x
  validations:
    required: true

- type: input
  id: wings-version
  attributes:
    label: Wings Version
    description: Version number of your Wings (latest is not a version)
    placeholder: 1.x.x
  validations:
    required: true

- type: input
  id: panel-logs
  attributes:
    label: Panel Logs
    placeholder: "https://bin.ptdl.co/"
  validations:
    required: true

- type: input
  id: wings-logs
  attributes:
    label: Wings Logs
    placeholder: "https://ptero.co/"
  validations:
    required: true

- type: input
  id: server-os
  attributes:
    label: Server OS
    placeholder: "Ubuntu 20.04"
  validations:
    required: true

- type: input
  id: computer-os
  attributes:
    label: Your Computer's OS
    placeholder: "Windows"
  validations:
    required: true

- type: input
  id: browser
  attributes:
    label: Browser
    placeholder: "Google Chrome"
  validations:
    required: true
    
- type: input
  id: php-version
  attributes:
    label: PHP Version
    placeholder: "8.0.5"
  validations:
    required: true

- type: textarea
  id: docker-info
  attributes:
    label: Information regarding docker
    description: "The info returned from `docker info`"
    render: bash
  validations:
    required: true

- type: textarea
  id: kernel-info
  attributes:
    label: Information regarding docker
    description: "The info returned from `uname -a`"
    render: bash
  validations:
    required: true

- type: textarea      
  id: actual-behavior
  attributes:
    label: Actual Behavior
    description: What actually happened instead
    placeholder: Server crashed with error X
  validations:
    required: true

- type: textarea          
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: What did you expect to happen
    placeholder: Install the server, start it, play
  validations:
    required: true

- type: textarea       
  id: reproduce-steps
  attributes:
    label: Steps To Reproduce
    description: Step by step what to do to cause the issue
    placeholder: |
      Step 1 Set version to latest
      Step 2 install
      Step 3 Receive error X or Y
  validations:
    required: true