name: Static Analysis

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"

jobs:
  tests:
    name: Static Analysis
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1]
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: bcmath, cli, curl, gd, mbstring, mysql, openssl, pdo, tokenizer, xml, zip
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist

      - name: Analyze
        run: vendor/bin/phpstan analyse
        if: ${{ always() }}
