name: Lint

on:
  push:
    branches:
      - "develop"
      - "1.0-develop"
  pull_request:
    branches:
      - "develop"
      - "1.0-develop"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
          coverage: none

      - name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
